<a href="https://colab.research.google.com/github/mittalichugh/bigdata/blob/main/labeval_group2_202301036.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
arr=np.array([10,52,62,16,16,54,4,5,3])
print(np.sort(arr))


[ 3  4  5 10 16 16 52 54 62]


In [7]:
arr=np.array([10,52,62,16,16,54,453])
sorted=np.sort(arr)
smallest=sorted[:4]
print("the 4 smallest elements are",smallest)

the 4 smallest elements are [10 16 16 52]


In [15]:
arr = np.array([10, 52, 62, 16, 16, 54, 453])
ind = np.argsort(arr)
print(ind)

[0 3 4 1 5 2 6]


In [14]:
import numpy as np
arr1= np.array([10,52,62,16,16,54,453])
su_arr =np.sort(arr1);
uv_arr =np.unique(su_arr)
print(su_arr[-5:])

[ 16  52  54  62 453]
